### ISSUE TITLE
Complete the cranking instruction, storing an aggregator and only allowing observation to move x amount per update

### ISSUE THREAD

**Issue by metaproph3t** [metaDAOproject/futarchy#122]

**Comment by Henry-E** [comment]
It depends whether the plan is to
- update once per transaction / call to the clmm-twap program
- or once per oracle observation, taking into account the time difference between each oracle observation, which if it's been a while since the last update could include a bunch of changes.

If it's the first one then it's a lot simpler but less reflective of reality.

re: https://github.com/metaDAOproject/futarchy/issues/121

If you want to know what index the ring buffer is currently at it's stored on pool state [`observation_index`]( https://github.com/raydium-io/raydium-clmm/blob/master/programs/amm/src/states/pool.rs#L90), you probably already know this. Just get that and then loop backward through the array until hitting a matching last observed `block_timestamp`.
