### ISSUE TITLE
Remove the ability to mint conditional tokens after finalization

### ISSUE THREAD

**Issue by 0xbigz** [metaDAOproject/futarchy#29]
if the proposal has been finalized to pass, i think you shouldn't be allowed to continue to mint fMETA/fUSDC from META (just the pass conditionals). Otherwise users can generate as much fMETA as they like after finalization. 

This also makes it more symmetric with the redeem process after finalization and is more fork friendly: the conditional fail diehards can form a community around their fMETA and pUSDC from closing their pMETA. fMETA can then carry on as if the proposal didnt pass.

**Comment by metaproph3t** [comment]
huh, I hadn't thought of the community-forming-around-forks idea, that's super interesting

this would be pretty technically easy to implement, just add a check [here](https://github.com/metaDAOproject/meta-dao/blob/c88a8605cdc0d2ece4dcb25d6a0c3a89bbf7c79b/programs/conditional_vault/src/lib.rs#L372-L376) that vault status is active

I wonder if this could be used to try to bribe ppl - like "don't sell any of your pMETA and I'll give you $100," or if you could get ppl to lock in pMETA to a smart contract so that they literally can't sell

**Comment by metaproph3t** [comment]
no longer am a fan of community-forming-around-forks idea, but I think this could be helpful for security

**Comment by metaproph3t** [comment]
Realized that you need to be able to mint to do arbitrages in finalized markets

**Comment by 0xbigz** [comment]
right

> Realized that you need to be able to mint to do arbitrages in finalized markets

but you dont need to mint fail token if pass market was finalized

**Comment by Henry-E** [comment]
It's surely more complicated to change the mint logic to only mint one of the pass or fail market once the proposal has been finalized than to just mint both and leave the code as is. Is there a downside if both are minted?
