### ISSUE TITLE
Weird node based import messes with yarn

### ISSUE THREAD

**Issue by Henry-E** [metaDAOproject/futarchy#54]
https://github.com/metaDAOproject/futarchy/blame/593ae6ad449f9110b10087eb0ceebc86020ee3be/package.json#L16

I don't have a huge understanding of the mess that is npm and yarn but this line messes with any attempts to run scripts using yarn. Yarn goes to the wrong spl-token package, even though there's a node based alias and just ignores the correct spl-token library. 

Practically speaking deleting the package from package.json and/or running npm install worked in terms of getting the script to import the correct version of spl-token but then when it came to either compiling or running the scripts using yarn stuff just started to break again.

**Comment by jshiohaha** [comment]
Hey @Henry-E , thanks for the comment on the possible issue. Could you further explain what issue you're experiencing? I'm not sure I totally understand what you mean because afaik, none of the scripts actually use the older aliased version? ([github search](https://github.com/search?q=repo%3AmetaDAOproject%2Ffutarchy%20%22%40solana%2Fspl-token-018%22&type=code)). 

When I run `yarn`, I can see both the newer version of `@solana/spl-token` and the aliased older version. Here's a pic of my `node_modules` folder after running `yarn`:

<img width="275" alt="Screenshot 2024-03-08 at 23 40 22" src="https://github.com/metaDAOproject/futarchy/assets/10272973/5f15fcc6-5115-4c50-9569-3d1c86734b53">
<br/><br/>

**Comment by jshiohaha** [comment]
In principle, I do agree it would be best to consolidate `@solana/spl-token` versions, but I believe this would require a few more changes around the repo.

When creating the PR you referenced, I was trying not to increase scope.

**Comment by jshiohaha** [comment]
For reference, here's an example of a script that runs perfectly fine under the current repository conditions:

```typescript
import {
  ASSOCIATED_TOKEN_PROGRAM_ID,
  TOKEN_PROGRAM_ID,
  getAssociatedTokenAddress,
} from "@solana/spl-token";

import { PublicKey, Keypair } from "@solana/web3.js";

const main = async () => {
  const mint = new PublicKey("METADDFL6wWMWEoKTFJwcThTbUmtarRJZjRpzUvkxhr");
  const owner = Keypair.generate();

  const ata = await getAssociatedTokenAddress(
    mint,
    owner.publicKey,
    true,
    TOKEN_PROGRAM_ID,
    ASSOCIATED_TOKEN_PROGRAM_ID
  );

  console.log("ata: ", ata.toBase58());
};

main();
```

To reproduce, 

1. add this code in a file,
2. update the [Anchor.toml](https://github.com/metaDAOproject/futarchy/blob/main/Anchor.toml) scripts,
3. and run the following with whatever valid cluster value you want: `anchor run <script_name> --provider.cluster <cluster>`

Hope that helps!

**Comment by jshiohaha** [comment]
Ok, so it looks like the initial reason I added the older package alias isn't actually needed. The same function exists in the regular `@solana/spl-token` package,  I just have to re-order some parameters.

I'll update and submit a new PR to resolve.
