### ISSUE TITLE
Design Meta Data Program

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/futarchy#94]
Discuss with team for updating settings, what fields etc.

**Comment by LukasDeco** [comment]
Storing convo from discord here for record keeping:
- Metadata will be key-value storage with no strict checks on key names
- UI/SDK will be responsible for rendering data based on the keys as it sees fit
- token metadata to be fetched from token metadata program
- waiting to hear potentially more feedback from other parties regarding metadata program if there are adjustments wanted to MetadataItem account or elsewhere

**Comment by Henry-E** [comment]
Alright [here's the PR](https://github.com/metaDAOproject/futarchy/pull/101) for the metadata program. It's still in draft format, no tests or anything added yet till I get some feedback on stuff like variable names, design, nitpicks from @metaproph3t . 

From chatting to Lucas really all we'll be storing using this account is
- DAO name
- DAO description
- Links / socials

For simplicity as well we're using Vectors, this means no zero-copy accounts, therefore the metadata file size will be limited to about 2kb max. Maybe could be pushed a bit higher but since we're storing so little data there it should be fine for now.

**Comment by metaproph3t** [comment]
Closing this for now
